# Generated by Django 5.2.1 on 2025-06-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('tracking', 'Tracking'), ('admin', 'Admin')], default='enquiry', max_length=20),
        ),
    ]
