# Generated by Django 5.2.1 on 2025-08-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superadmin', 'Superadmin'), ('survey-admin', 'Survey Admin'), ('sales', 'Sales')], default='user', max_length=20),
        ),
    ]
