# Generated by Django 5.2.1 on 2025-08-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_role_remove_customuser_role_customuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enable_email_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
