# Generated by Django 5.2.1 on 2025-08-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_customuser_enable_email_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enable_email_receiver',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
