# Generated by Django 5.2.1 on 2025-08-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='send_mail_user',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
