# Generated by Django 5.2.1 on 2025-09-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_customuser_send_mail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='send_mail_user',
        ),
    ]
