# Generated by Django 5.2.1 on 2025-08-20 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('serviceType', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('recaptchaToken', models.TextField()),
                ('refererUrl', models.URLField(blank=True, null=True)),
                ('submittedUrl', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('contact_status', models.CharField(blank=True, choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=20, null=True)),
                ('reached_out_whatsapp', models.BooleanField(blank=True, default=False, null=True)),
                ('reached_out_email', models.BooleanField(blank=True, default=False, null=True)),
                ('survey_date', models.DateTimeField(blank=True, null=True)),
                ('salesperson', models.ForeignKey(blank=True, limit_choices_to={'role': 'sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='contact_enq_created_b6ecb0_idx')],
            },
        ),
    ]
