# Generated by Django 5.2.1 on 2025-08-20 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['salesperson'], name='contact_enq_salespe_ec7fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['contact_status'], name='contact_enq_contact_2116b9_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['survey_date'], name='contact_enq_survey__369145_idx'),
        ),
    ]
