# Generated by Django 5.2.1 on 2025-08-22 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_enquiry_contact_enq_salespe_ec7fd7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='enquiry',
            name='contact_enq_salespe_ec7fd7_idx',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['assigned_user'], name='contact_enq_assigne_fc4384_idx'),
        ),
    ]
