# Generated by Django 5.2.1 on 2025-08-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_enquiry_contact_enq_salespe_ec7fd7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='contact_status_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
