# Generated by Django 5.2.1 on 2025-10-02 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additional_settings', '0001_initial'),
        ('contact', '0004_enquiry_contact_status_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('company', 'Company')], max_length=20, null=True)),
                ('is_military', models.BooleanField(blank=True, default=False, null=True)),
                ('salutation', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], max_length=10, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('survey_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('goods_type', models.CharField(blank=True, choices=[('household', 'Household'), ('commercial', 'Commercial')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('non_active', 'Non Active')], default='active', max_length=20, null=True)),
                ('survey_start_time', models.TimeField(blank=True, null=True)),
                ('survey_end_time', models.TimeField(blank=True, null=True)),
                ('work_description', models.TextField(blank=True, null=True)),
                ('include_vehicle', models.BooleanField(blank=True, default=False, null=True)),
                ('include_pet', models.BooleanField(blank=True, default=False, null=True)),
                ('cost_together_vehicle', models.BooleanField(blank=True, default=False, null=True)),
                ('cost_together_pet', models.BooleanField(blank=True, default=False, null=True)),
                ('same_as_customer_address', models.BooleanField(blank=True, default=False, null=True)),
                ('origin_address', models.TextField(blank=True, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_state', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('pod_pol', models.CharField(blank=True, max_length=100, null=True)),
                ('multiple_addresses', models.BooleanField(blank=True, default=False, null=True)),
                ('packing_date_from', models.DateField(blank=True, null=True)),
                ('packing_date_to', models.DateField(blank=True, null=True)),
                ('loading_date', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('etd', models.DateField(blank=True, null=True)),
                ('est_delivery_date', models.DateField(blank=True, null=True)),
                ('storage_start_date', models.DateField(blank=True, null=True)),
                ('storage_frequency', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('storage_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('general_owner_packed', models.BooleanField(blank=True, default=False, null=True)),
                ('general_owner_packed_notes', models.TextField(blank=True, null=True)),
                ('general_restriction', models.BooleanField(blank=True, default=False, null=True)),
                ('general_restriction_notes', models.TextField(blank=True, null=True)),
                ('general_handyman', models.BooleanField(blank=True, default=False, null=True)),
                ('general_handyman_notes', models.TextField(blank=True, null=True)),
                ('general_insurance', models.BooleanField(blank=True, default=False, null=True)),
                ('general_insurance_notes', models.TextField(blank=True, null=True)),
                ('origin_floor', models.BooleanField(blank=True, default=False, null=True)),
                ('origin_floor_notes', models.TextField(blank=True, null=True)),
                ('origin_lift', models.BooleanField(blank=True, default=False, null=True)),
                ('origin_lift_notes', models.TextField(blank=True, null=True)),
                ('origin_parking', models.BooleanField(blank=True, default=False, null=True)),
                ('origin_parking_notes', models.TextField(blank=True, null=True)),
                ('origin_storage', models.BooleanField(blank=True, default=False, null=True)),
                ('origin_storage_notes', models.TextField(blank=True, null=True)),
                ('destination_floor', models.BooleanField(blank=True, default=False, null=True)),
                ('destination_floor_notes', models.TextField(blank=True, null=True)),
                ('destination_lift', models.BooleanField(blank=True, default=False, null=True)),
                ('destination_lift_notes', models.TextField(blank=True, null=True)),
                ('destination_parking', models.BooleanField(blank=True, default=False, null=True)),
                ('destination_parking_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='contact.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('poe', models.CharField(blank=True, max_length=100, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_addresses', to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('move_status', models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='new', max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_settings.currency')),
                ('handyman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_settings.handyman')),
                ('packing_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_settings.packingtype')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_settings.room')),
                ('volume_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_settings.volumeunit')),
                ('weight_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_settings.weightunit')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance', models.BooleanField(blank=True, default=False, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('transport_mode', models.CharField(blank=True, choices=[('road', 'Road'), ('air', 'Air'), ('train', 'Train')], default='road', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='survey.survey')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additional_settings.vehicletype')),
            ],
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['enquiry'], name='survey_surv_enquiry_0179b2_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['survey_id'], name='survey_surv_survey__470533_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['created_at'], name='survey_surv_created_d8081f_idx'),
        ),
        migrations.AddIndex(
            model_name='destinationaddress',
            index=models.Index(fields=['survey'], name='survey_dest_survey__63f764_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['survey'], name='survey_arti_survey__e52ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='survey_arti_created_4b4691_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['survey'], name='survey_vehi_survey__0a3f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['created_at'], name='survey_vehi_created_358dc6_idx'),
        ),
    ]
