# Generated by Django 5.2.1 on 2025-10-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0001_initial'),
        ('survey', '0002_survey_email_survey_first_name_survey_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='behavior_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='feeding_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='transport_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccination_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='survey_arti_categor_645a78_idx'),
        ),
    ]
