# Generated by Django 5.2.1 on 2025-10-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0001_initial'),
        ('survey', '0003_pet_behavior_notes_pet_feeding_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='survey_arti_categor_645a78_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['room'], name='survey_arti_room_id_ddab24_idx'),
        ),
    ]
