# Generated by Django 5.2.1 on 2025-10-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_article_survey_arti_categor_645a78_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='survey.survey'),
        ),
    ]
