# Generated by Django 5.2.1 on 2025-05-22 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(choices=[('air', 'Air Cargo'), ('door_to_door', 'Door To Door Cargo'), ('land', 'Land Cargo'), ('sea', 'Sea Cargo')], max_length=20)),
                ('receiver_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('recipient_address', models.TextField()),
                ('recipient_country', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=255)),
                ('number_of_packages', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('cargo_ref_number', models.CharField(max_length=100, unique=True)),
                ('tracking_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('collection_date', models.DateField()),
                ('time_of_departure', models.TimeField()),
                ('time_of_arrival', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_customers.addcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_content', models.TextField()),
                ('status_date', models.DateField()),
                ('status_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='add_jobs.job')),
            ],
        ),
    ]
