# Generated by Django 5.2.1 on 2025-06-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='time_of_arrival',
        ),
        migrations.RemoveField(
            model_name='job',
            name='time_of_departure',
        ),
        migrations.AddField(
            model_name='job',
            name='date_of_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='date_of_departure',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='cargo_ref_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
